
import Head from 'next/head'


const Home = () => {
  return (
    < >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <h1>Welcome to the layout component...</h1>
    </>
  )
}

export default Home

